<a href="https://colab.research.google.com/github/hamza-bangash/NLP/blob/main/nlp_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IMDB_Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
# Problem 1
# Apply all the preprocessing techniques that you think are necessary

In [5]:
from bs4 import BeautifulSoup
def remove_html_tags(text):
    return BeautifulSoup(text,"html.parser").get_text(separator=" ")

In [6]:
import re

def remove_urls(text):
 return re.sub(r'https?://\S+|www\.\S+','',text)

In [7]:
def remove_backsalsh(text):
    return text.replace("\n"," ")

In [8]:
import spacy

In [9]:
nlp = spacy.load("en_core_web_sm", disable=["ner", "parser"])

In [10]:
def preprocessing_pipeline(text):
    doc = nlp(text)

    tokens = [token.lemma_.lower() for token in doc if not token.is_stop and not token.is_punct]

    return tokens

In [11]:
df['review'] = df['review'].apply(remove_html_tags)

In [12]:
df['review'] = df['review'].apply(remove_urls)

In [13]:
df['review'] = df['review'].apply(remove_backsalsh)

In [15]:
df['review'] = df['review'].apply(preprocessing_pipeline)

In [16]:
df.head()

                                              review sentiment
0  [reviewer, mention, watch, 1, oz, episode, hoo...  positive
1  [wonderful, little, production,  , filming, te...  positive
2  [think, wonderful, way, spend, time, hot, summ...  positive
3  [basically, family, little, boy, jake, think, ...  negative
4  [petter, mattei, love, time, money, visually, ...  positive

In [17]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

In [18]:
total_words = df['review'].str.len().sum()

In [19]:
total_words

np.int64(5223178)

In [20]:
vocabulary = set([words for row in df['review'] for words in row])

In [21]:
vocabulary

{'meerkat',
 'wilhelm',
 'tutankhamen',
 'nocoletta',
 'afterwhich',
 'qualité',
 'e.g',
 'sanders)jealous',
 'nerves.(sense',
 'seriously--',
 'tomeihere',
 'obtrusively',
 'grading',
 'alert----------------------------',
 '4/20/1934',
 'bickford(matt',
 'fetes',
 'slitheen',
 'mid-1961',
 'buggy',
 'bluer',
 'conaway)daughter',
 'brideless',
 'laudenbach)who',
 'pertfectly',
 'myth',
 'cloony',
 '571',
 'goombah',
 'uncynical',
 'barin',
 'steeeeee',
 'majestys',
 '7.-100',
 'govich',
 'cowboys',
 'flint',
 'crafted',
 'patrician',
 'vista',
 'film.i',
 '1600',
 'cabot',
 'isrelai',
 'imdber',
 'natch',
 '12$.',
 '66p',
 'incarcerate',
 'clinched',
 'authorisation',
 'theorie',
 "b'day",
 'keen',
 'physiological',
 'allocate',
 'decaffeinated',
 'sickboy',
 'telecommunicational',
 'videotape',
 "l'arrosseur",
 'aasmaan',
 'dv',
 'hodgepodge',
 "l'atlante",
 'trueblood',
 'disappointed.7',
 'bryce',
 'ya?since',
 '~not~',
 'loudhailer',
 'cannery',
 'chris_m_grant',
 'era)were',
 'everest',
 'gnawing',
 'devestated',
 'basalt',
 'bubble',
 'friends),awful',
 'unwatchable',
 'tenniel',
 'sigurðusson',
 'spoilerama',
 'fargas',
 'motorama',
 'boleslowski',
 'fahrt',
 "bad'--",
 'talal',
 'undershort',
 'president(but',
 'malika',
 'b.b.e.',
 'bullet',
 'folles',
 'extraction',
 'psi',
 'earthworm',
 'gregorian',
 'yashere',
 'brennaman',
 'mockumentarie',
 'personailtie',
 'compassionately',
 'contact@fightrunner.co.uk',
 'floozy',
 'buccaneer',
 'insturmental',
 'goofball',
 'howlariously',
 'extrovert',
 'ally-',
 'habsburgs',
 'einon',
 'ever(and',
 'orth',
 'egoism',
 'buffalo',
 '--very',
 'foundations',
 'zouganelis',
 'squashy',
 'demerit',
 '814',
 'beneficence',
 'perry',
 'consign',
 'doran(claudia',
 'tomcat',
 'prospero',
 'notte',
 'passingly',
 'wopr',
 'konchalovksy',
 'marsden(disturbing',
 'coachly',
 'degenerate',
 'maclaughlin',
 'disorienting',
 'recognise',
 'jeremey',
 'springerland',
 'kno',
 'konradi',
 'mocumentarie',
 'mendelito',
 'upendra',
 'wald',
 'paola',
 'zucco)leaves',
 'flywheel',
 'epyon',
 'roddenberry',
 'elephants',
 'sexist',
 'phaedra',
 'unadaptable',
 'goswami',
 'repartee',
 'throng',
 'sieger',
 'increably',
 "the'd",
 'rancor',
 'firelight',
 'watchmaker',
 '5)the',
 'bounty',
 'bromwell',
 'spicy',
 'hark',
 'girl(marie',
 '---main',
 'kornbluth',
 'apples',
 'f**ker',
 'throaty',
 'nazan',
 'ribbing',
 'assassins',
 'slight1y',
 'graphic.however',
 'gaius',
 'odysseus',
 '(sic',
 'caveat',
 'cnnnn',
 'myself(thankfully',
 'drowning',
 'wexford',
 'gobblygook',
 'witchburn',
 'courting',
 'boater',
 'harris(baloo',
 'voluptuousness',
 'lakers',
 'mattson',
 '21',
 'renyolds',
 'virzi',
 'cheapie',
 'sawyer',
 'typical-',
 'equippe',
 '22:18',
 'chignon',
 'communicate',
 'alvaro',
 'jibe',
 'hallan',
 'burtonesque',
 'iamerace',
 "miss-'em",
 'concho',
 'dogma95',
 '2,5',
 'schmoke',
 'rebuild',
 'blanco',
 'mctaketh',
 'mogambo',
 'baastard',
 '-quirky',
 'langhella',
 'hellfire',
 'craftier',
 'movie,',
 'brocco',
 'stubbly',
 'bloodymonday',
 'stagestruck',
 'overfill',
 '\x84old',
 'bharatnatyam',
 'roa',
 'gloopy',
 'm.davis',
 'guervara',
 "(i've",
 'snowglobe',
 'forget--',
 'chubby',
 'dignity',
 'mende',
 'included',
 'parnell',
 'blodwyn',
 'nerd-',
 "k'sun",
 'concerted',
 'sanderson',
 '42',
 'stagnate',
 'tsotg',
 'industrialise',
 'saxon',
 'probably',
 'dimitriades',
 'sklar',
 'deewana',
 'virual',
 'ninjo',
 'régulier',
 'appomatox',
 'rygel',
 'preachy',
 'bert',
 'ghetto',
 'zorn',
 'opuse',
 'complicated',
 'wonderworks',
 'goddammit',
 'greasepaint',
 'massively',
 'lama',
 'blockbusters(jumanji',
 'evelyn',
 'led',
 'deneuvue',
 'teignmouth',
 'mathematical',
 'schneebaum',
 'talents(did',
 'burke',
 '243',
 'cooperative',
 'jalouse',
 'bowness',
 'burgundians',
 'kel',
 'sprinting',
 'b-52s',
 'unbroken',
 'yue',
 'overtone',
 'detractor',
 'springboks',
 'frekin',
 'sportman',
 'makavajev',
 'stylus',
 'phriends',
 'sadomasochism',
 'films)but',
 'truthful',
 'bother',
 'darla',
 'lost,24',
 'generalship',
 'proofread',
 'carnaby',
 "diploma!you've",
 'aloysius',
 'historicaly',
 'roeper',
 'raiders',
 'safiya',
 'bolliwood',
 'barbarella',
 'massacre"-feeling',
 'chilean',
 'lahti',
 'butterball',
 'want;-',
 'uncompleted',
 'methought',
 'fantsastic',
 'simpkins',
 'landholding',
 'minghella',
 'acclimatisation',
 'licious',
 'secrets\x97director',
 '1200f',
 'spinetingle',
 'faulknarian',
 'nose)which',
 'installation',
 'tawt',
 '-sheet',
 '1,000,000,000,000',
 'uncontainable',
 'hurry',
 'bronowski',
 'hailsham',
 'shrieff',
 'ashok',
 'verdone',
 'for.he',
 'waaaaaaaaaaay',
 'corrective',
 'methodical',
 'remaining',
 'xer',
 'destructively',
 'introductory',
 'undeserving',
 'iceholes',
 'sleepwalk',
 'meritt',
 'me!!!!it',
 'g*y',
 'fatima',
 'transom',
 'fleetingly',
 'escalation',
 'though(no',
 'distantiate',
 'lapinski',
 'irm',
 'meldrick',
 'plumps',
 "ff'd",
 'spaced',
 'uncomplex',
 'mera',
 'sauropod',
 'kreestos',
 'pyrotechnical',
 'this(the',
 'abominal',
 'truant',
 'beebe',
 'scruno',
 'mannish',
 'dory',
 'storszek',
 'pre-"murder',
 'bolero',
 'casares',
 'amphitheater',
 'nimitz',
 'omosis',
 'c.h.o.m.p.s.',
 'equation',
 'playin',
 'ns',
 'circularly',
 'lindbergh',
 'enlighten',
 'weekly',
 'breaking',
 'guillotines',
 'kemosabe"',
 'serle',
 'coed',
 'siamese',
 'zomg',
 'jf',
 'miracolo',
 'attachés',
 'ruocco',
 'kindness',
 'ladislaw',
 'bigha',
 'militiaman',
 'brook',
 'lucrative',
 'community-',
 'tumultuous',
 'calthorpe',
 'achile',
 'wooer',
 'command).he',
 'lalwani',
 'dress)--the',
 'diarhhoea',
 'yutte',
 'pfeten',
 'ratty',
 'perv',
 'marit',
 'masterton',
 "arn't",
 'curitz',
 'lait',
 'yonfan',
 'juran',
 'swigert',
 'secretary',
 'crutchley',
 'nov.',
 'aaton',
 'prezzo',
 'decompression',
 'stereotypical',
 'unearp',
 'sergei(rade',
 'h.s.',
 'werewolves',
 'benton',
 'rêve',
 'neanderthalian',
 'kelemen',
 'boulevard',
 'yaargh',
 'charlotte',
 'mfumu',
 'punky',
 'lindenmuth',
 'trauma',
 'provoking"-',
 'career("estranha',
 'york',
 'mystery-',
 'whiteley',
 'chicks-',
 'bridges(the',
 'céu',
 'maltreat',
 'magic-',
 'mwak',
 'softcore',
 'unstoppably',
 'stocky',
 'monogrammed',
 'tannenbaum',
 'lidón',
 'robers',
 'unemotional',
 'mihalka(my',
 'unmedicated',
 'portrait',
 'ugo',
 'satsuki',
 'pterdactyl',
 '2772',
 'winter',
 'lugusi',
 'convalesce',
 'prune',
 'referend',
 'didgeridoo',
 'seaton',
 'nilo',
 'affectedly',
 'kawashima',
 'stuie',
 'cardiologist',
 'badel',
 'mnd',
 'funking',
 'scool',
 'p3n1',
 'alaska',
 'suspecion',
 'rown',
 'stalkers',
 'muldaur(who',
 'buddhists',
 'pi',
 'szubanski',
 'dabneys',
 'derision).the',
 'beckett',
 'lübeck',
 'wood(without',
 'counterfiet',
 'wilshire',
 'schoolers/',
 'apoligize',
 'gondola',
 'interesting',
 'nakada',
 'bunkum',
 'subtitling',
 '--"hey',
 'there!he',
 '-9/10',
 'wilkinson',
 'workday',
 'either)chan',
 'modus',
 '1886',
 'dagher',
 'ugc',
 'hrpuff',
 'reid',
 'machism',
 'overal',
 'life??cause',
 'mowbray',
 'wattis',
 'cutdown',
 'poisoning"',
 'penzance',
 'killter',
 'milieus',
 'mallwart',
 'hun',
 'ie',
 'midscreen',
 'gym--',
 'century-',
 '-horrible',
 'yugoslavia',
 'sephiroth',
 'dominee',
 'cooooo',
 'milion',
 'plagiarist',
 'ggooooodd',
 'flatly',
 'fault(he',
 'bullpen',
 'girardeau',
 'schemes',
 'mouth-',
 'btk',
 'oratorio',
 'birdwatching',
 'rolento',
 'daleks',
 'root',
 'quantrill',
 'avsp',
 'expatriate',
 'clemen',
 'shops',
 'gutless',
 'blayde',
 'boorish',
 'vol.2',
 'failsafe',
 'super8',
 'endo',
 'layla',
 'insolence',
 'underdog',
 'mahiro',
 'leak',
 'christenson',
 'safran',
 'cheapened',
 'leet',
 'sartain',
 'underfunded',
 'portugal',
 'nykvist',
 'gomer',
 'lawyere',
 'meditated',
 'trotting',
 'graphics?people',
 'dibiase|c|/w',
 'u.',
 'photophone',
 'survivial',
 'crabb',
 'condominium',
 'walker',
 'camra',
 'beuregard',
 'nuna',
 'hilarity',
 'shtrafnoy',
 'pharoahs',
 'practicable',
 'eighth',
 'treater',
 'diet',
 'alton(timothy',
 '-skinned',
 'chocked',
 'agaaaain',
 'jhj',
 'cynthis',
 'actor(sara',
 'verica',
 'kurosawa',
 'slack',
 'basic',
 'metzger',
 'kaleidiscopic',
 'guerin',
 'bracknell',
 'course',
 'sokurov',
 'stamos(jesse',
 'thrall',
 'akmed',
 'spivs',
 'transliteration',
 'lachaise',
 'waco',
 'aninmation',
 'tiller',
 'wabi',
 'lemuel',
 'shoulin',
 'childrens',
 'hackenstien',
 'sammy',
 'regeneration',
 'invinoveritas1@aol.com',
 'capelja',
 'eek',
 'u.s.-backed',
 'payola',
 'preachie',
 'mature',
 'worf',
 'referendum',
 '9pm/8pm',
 'tetsudô',
 'bizzarre',
 'megalomaniac',
 'movie\x97which',
 'acrylic',
 'napoleon`s',
 'gayle',
 'r&h',
 'kent',
 'batmite',
 'mccool',
 'ashram',
 'raskin',
 'melt',
 'cheddarfest',
 'isten',
 'dream-',
 'lolita',
 'busboy',
 's*%@',
 'dusan',
 'desert',
 'crossbow',
 '1891',
 'supervillain',
 'more--',
 'cleaning',
 'bankes',
 'mush',
 'waller',
 'feirstein',
 'fathomable',
 'freedom',
 'ayanna',
 'ghettoism',
 'rearise',
 'lancelot',
 'shakiness',
 'kelada',
 'maleficent',
 'streamlined',
 'ø',
 'caliban',
 'pray',
 'sparce',
 'mépris',
 'london--',
 'smoke(yes',
 'absolutly',
 'tunny(lori',
 'saxaphone',
 'ballbuste',
 'harmon',
 'dorina',
 '3d.',
 'discussions(or',
 'elah',
 'garbage)-i',
 'cripe',
 'marriott',
 'moves(single',
 'grieves',
 'you!---i',
 'arrested',
 'deedy',
 'buena',
 'martians(here',
 'neale',
 'fearless',
 'pensyltucky',
 'knife(',
 'quiznos',
 'remorseless',
 'sounder',
 'cutest',
 'bulgarians',
 'chill',
 'overstudiously',
 'reconsider',
 'dominque',
 'overdue',
 'persevere',
 'collerton',
 'sarah",worth',
 'gieldgud',
 'throwers',
 'complexion',
 'snoozef',
 'mcintosh',
 'mosely',
 'vulnerablity',
 'hol',
 '-your',
 'offending',
 'shwaas',
 'man),but',
 'nack',
 'baronland',
 'bahumbag',
 'occupe',
 '12/17/01',
 'harks',
 'studios',
 'replicate',
 'mchales',
 'risto',
 'unauthentic',
 'serie',
 'him\x97strength',
 'museums',
 'imdb.com',
 '2035',
 'grell',
 'undescribable',
 'vice-',
 'hapless',
 'gc161',
 'osiric',
 'plo(something',
 'martindale',
 'receptor',
 'marek',
 "collaborator'(zoe",
 '55min',
 'jupiter',
 'putrescent',
 'flippant',
 'brigadier',
 'centralized',
 'undoubte',
 'music-',
 'meaninglessly',
 'ardant',
 'peachtree',
 'quickening',
 'secunda',
 'goreporn',
 'doctor(robert',
 'h.r.giger',
 'dissapionte',
 'orphans',
 'bad-\x97if',
 'earthiness:"the',
 'ady',
 'interpretations',
 'toughie',
 'lawston',
 'leaflet',
 'lengthy',
 '1960',
 'northanger',
 'unfriendliness',
 'all.and',
 's.c.u.b.a.',
 'yusuf',
 'flavorless',
 'majeske',
 'zaillian',
 'skitz',
 'bullseye',
 'spell(',
 'dostoyevskian',
 'blóðbönd',
 '7.oo',
 "youv'e",
 'waterlilie',
 'slitting',
 'lulling',
 'avtaar',
 'taraf',
 'vs.',
 'shola',
 'jikô',
 'was.(sarcasm',
 'politicial',
 'artfully',
 "blues'is",
 'delarua',
 '545',
 'exhibit',
 'garda',
 'hellishly',
 'disasters',
 'flatness',
 'stanislawa',
 'mcgovernisms',
 'instead--',
 'genus',
 '"--emperor',
 'pfifer',
 'tryfon',
 'bally',
 'p9fos',
 'barbier',
 "welsh!i'm",
 'martineau',
 'kenshiro',
 'ood',
 'saladin',
 'myshkin',
 'mahabharata',
 'letting',
 'watchowski',
 'versprechen',
 'baurki',
 'almodovar',
 'beseige',
 'zelinas',
 'tele',
 'eternity',
 'cubical',
 'woodcourt',
 "blow'em",
 'anjana',
 'shoulder',
 'windstruck',
 'varela',
 'recalcitrant',
 'film)assert',
 'magi',
 'avoidable',
 'price--',
 'negri',
 'kumarswamypillai',
 'speedway',
 'aap',
 'naddel',
 'triumphal',
 'stratovarius',
 'tate',
 'vicariously',
 'pfeffier',
 'armstrong(who',
 'beganing',
 'turner(while',
 'uribe',
 'storyline.it',
 'tukel',
 'newberry',
 'underaged',
 'festering',
 'blood",but',
 'dicks',
 'runkle',
 'courttv',
 'wender',
 'ehelhell',
 '(*sigh',
 'bitchin',
 'negrophile',
 'jerkwater',
 'orbison',
 'gether',
 'stuff-',
 'thimothy',
 'orin',
 'sebei',
 'beslon',
 'dobel',
 'breathtaking',
 'graver',
 'gripper',
 "mean'n'lean",
 'gowky',
 'fascist(john',
 'niftily',
 'physco',
 'takeiuchi',
 'wantonness',
 'books-',
 'momentary',
 'vomitte',
 'shaggy',
 'm.d.',
 'megyn',
 "stillcouldn't",
 'disjoin',
 'pakistani',
 'glacier',
 'devanand',
 'anonymous(sometimes',
 'information\x97an',
 'panacea',
 'breoken',
 'mochanian',
 'waterston',
 'veto',
 'semebene',
 'm6',
 'spookishly',
 'sarte',
 'park(kinda',
 'sigfreid',
 'ferrigno',
 'indigent',
 'disposability',
 'latronic',
 'benito',
 'is\x97not',
 'belén',
 'frizzly',
 'demirkubuz',
 'busco',
 'welker',
 'blending',
 'gt',
 'yoyo',
 'apolitical',
 'dunnit',
 'hird',
 'chloe',
 'rossi',
 'videocover',
 'jailbait',
 'quigly',
 'unesco',
 'eventhough',
 'fusillade',
 'dreaming',
 'drago)but',
 'social',
 'synchronize',
 'camerlegno',
 'aaaaah',
 'giammati',
 'mitropa',
 'dogged',
 'italy),was',
 'dbz',
 'yale',
 'sixpack',
 'clair',
 'oversee',
 ...}

In [22]:
vocab_size = len(vocabulary)

In [23]:
vocab_size

106490

In [ ]:
# Problem 3
# Apply One Hot Encoding

In [ ]:
import numpy as np

In [ ]:
word_index = {word: i for i, word in enumerate(vocabulary)}

In [ ]:
def ohe(word):
  token= np.zeros(vocab_size,dtype=int)
  index = word_index[word]
  token[index] = 1
  return token

In [ ]:
one_hot_encoding = df['review'].apply(lambda row: [ ohe(token) for token in row])

In [ ]:
# Problem 4
# Apply bag words and find the vocabulary also find the times each word has occured

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
bagsofwords = CountVectorizer()

In [27]:
text = df['review'].str.join(' ')

In [28]:
text

0        reviewer mention watch 1 oz episode hook right...
1        wonderful little production   filming techniqu...
2        think wonderful way spend time hot summer week...
3        basically family little boy jake think zombie ...
4        petter mattei love time money visually stunnin...
                               ...
49995    think movie right good job creative original e...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic teach parochial elementary school nun...
49998    go disagree previous comment maltin second rat...
49999    expect star trek movie high art fan expect mov...
Name: review, Length: 50000, dtype: object

In [29]:
x = bagsofwords.fit_transform(text)

In [30]:
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4134344 stored elements and shape (50000, 89648)>

In [31]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

In [32]:


bigram = CountVectorizer(ngram_range=(2, 2))
X_bigram = bigram.fit_transform(text)

bigram_vocab = bigram.get_feature_names_out()
bigram_vocab_size = len(bigram_vocab)

print("Bigram vocabulary size:", bigram_vocab_size)

Bigram vocabulary size: 2615849

In [33]:
trigram = CountVectorizer(ngram_range=(3, 3))
X_trigram = trigram.fit_transform(text)

trigram_vocab = trigram.get_feature_names_out()
trigram_vocab_size = len(trigram_vocab)

print("triigram vocabulary size:", trigram_vocab_size)

triigram vocabulary size: 4704078

In [ ]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(text)

In [36]:
vocabulary = tfidf_vectorizer.get_feature_names_out()

In [37]:
vocabulary

array(['00', '000', '00000000000', ..., 'żmijewski', 'יגאל', 'כרמון'],
      dtype=object)

In [38]:
idf_scores = tfidf_vectorizer.idf_